### PR TITLE
Fixed typo

### PR DESCRIPTION
**Pull request by andycasey**
Also, this is **awesome**. I'm going to start adding code to make use of this functionality on the client end. I was just about to email you guys if there was going to be API access to libraries in the future, and then here we are!

### CODE REVIEW

**Comment by jonnybazookatone** [comment]
Thanks. If something isn't clear, let us know. Libraries are on accessible on BBB right now under your user account; http://adsabs.github.io/blog/ads-private-libraries/. Permissions in the UI should be included later, so some things might not be contextually clear.

I'm happy to contribute to the client if you open a branch specifically for the libraries.

**Comment by andycasey** [comment]
One question @jonnybazookatone: do you have a specific timeframe for when the old libraries will be transferred over to BBB? (And whether I'd be able to politely request for 1 or 2 old ones to be switched over early for "testing", rather than creating new ones)

**Comment by jonnybazookatone** [comment]
We plan the near future, it's at the top of the list. If you want to do it already, and you're happy with playing with the API, you can go ahead and do it using your dev token.

You just need to send a post request to 'v1/biblib/libraries', that contains the 'name', 'description', and 'bibcode' list. This'll create the library and insert the relevant bibcodes. So, you just need to pull the relevant libraries from classic or ADS 2.0.

For ADS classic you can export them with a custom print statement that just outputs the bibcodes. For 2.0 I guess you can do it via the client you wrote (?).

As for testing, I'd suggest you stub the response from the libraries asap so that you don't reach the API limit during development. I'm happy to pass on the type of responses you would get.

**Comment by andycasey** [comment]
Great, thanks @jonnybazookatone!

**Pull request merged**
